# Generated by Django 5.2.7 on 2025-10-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(max_length=30)),
                ('mobile_num', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_num',
            field=models.CharField(max_length=10),
        ),
    ]
